version: "3.7"
services:
  web:
    image: odoo:local
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    volumes:
      - "web-data:/var/lib/odoo"
      - "./odoo/:/etc/odoo/"
      - "./config/:/var/www/odoo/config/"
      - "./extra-addons/:/var/www/odoo/extra-addons/"
    environment:
      - USER=odoo
      - PASSWORD=odoo
    command: bash -c "/etc/odoo/odoo-bin -c /var/www/odoo/config/odoo.conf"


  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - db-data:/volumes/postgresql/data/pgdata

  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

volumes:
  web-data:
  db-data:

